version: 2.1

jobs:
  build:
    docker:
      - image: cimg/azure:2023.07
    steps:
      - run:
          name: az login using OIDC
          command: |
            az login \
                --service-principal \
                -u "${AZURE_CLIENT_ID}" \
                -t "${AZURE_TENANT_ID}" \
                --federated-token "${CIRCLE_OIDC_TOKEN}"
      - run: az vm list

workflows:
  run:
    jobs:
      - build:
          context:
            - oidc-azure
