version: 2.1

jobs:
  login-azure-with-oidc:
    docker:
      - image: cimg/azure:2023.07
    steps:
      - run:
          name: az login using OIDC
          command: |
            az login \
                --allow-no-subscriptions \
                --service-principal \
                --user "${AZURE_CLIENT_ID}" \
                --tenant "${AZURE_TENANT_ID}" \
                --federated-token "${CIRCLE_OIDC_TOKEN}"
      - run: az vm list

workflows:
  run:
    jobs:
      - login-azure-with-oidc:
          context:
            - OIDC-Azure
